version: "3"

services:
  db:
    image: postgres
    restart: always
  web:
    build: .
    restart: always
    environment:
      # Skip heroku settings
      - DOCKER=1
    env_file:
      - .env
    # Prevent gunicorn workers from blocking
    tmpfs: /tmp
    command: bash -c "
      python manage.py collectstatic --noinput
      && python manage.py migrate
      && gunicorn -w 3 panner.wsgi:application -b :8000"
    volumes:
      - .:/code
      - static:/code/staticfiles
    expose:
      - "8000"
    depends_on:
      - db
  proxy:
    image: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - static:/code/staticfiles
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

volumes:
  static: