version: "3"

services:
  db:
    image: postgres
    restart: always
  redis:
    image: redis
    restart: always
  web:
    build: .
    restart: always
    env_file:
      - .env
    # Prevent gunicorn workers from blocking
    tmpfs: /tmp
    command: bash -c "
      python manage.py collectstatic --noinput
      && python manage.py migrate
      && python manage.py loaddata people
      && gunicorn panner.wsgi -b :8000"
    volumes:
      - .:/code
      - static:/code/staticfiles
    expose:
      - "8000"
    depends_on:
      - db
      - redis
  proxy:
    image: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - static:/code/staticfiles
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

volumes:
  static: