# Generated by Django 2.2.2 on 2019-06-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=30)),
                ('reddit', models.CharField(blank=True, max_length=20)),
                ('spotify', models.CharField(blank=True, max_length=30)),
                ('twitter', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
