# Generated by Django 2.2.2 on 2019-06-28 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0003_auto_20190620_0333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram',
        ),
    ]
