# Generated by Django 2.2.2 on 2019-06-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0004_auto_20190628_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='line',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
