# Generated by Django 2.2.2 on 2019-06-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0005_profile_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='meetup',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
