# Generated by Django 2.2.3 on 2019-07-09 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0006_profile_meetup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='line',
        ),
    ]
